version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: microscope-minio
    ports:
      - "9000:9000"      # API порт
      - "9001:9001"      # Web Console порт
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped